name: 'publish crates'
description: 'Publish Rust crates on crates.io'
author: 'K. <kayo@illumium.org>'
branding:
  icon: box
  color: orange
inputs:
  path:
    description: 'Path to Rust crate or workspace'
    default: '.'
  args:
    description: 'Extra arguments for cargo publish'
    default: ''
  dry-run:
    description: 'Skip execution cargo publish'
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
