name: 'publish crates'
description: 'Publish Rust crates on crates.io'
author: 'K. <kayo@illumium.org>'
inputs:
  path:
    description: 'Path to Rust crate or workspace'
    default: '.'
  verify:
    description: 'Verify package before publish'
    default: 'true'
  dry-run:
    description: 'Do not upload crates'
    default: 'false'
  args:
    description: 'Extra arguments for cargo publish'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
